### ISSUE TITLE
Suggestions on compiling RGFW 

### ISSUE THREAD

**Issue by ColleagueRiley** [tonis2/cui#1]
I suggest that instead of modifying RGFW.c/.h, you add `RGFW_IMPLEMENTATION` as a cflag.
This is because RGFW is a newer library and is prone to important updates, so making it easier to change out would probably be better.

You can do this by changing:

``"cflags": "-fPIE"``
to 
`"cflags": "-fPIE -D RGFW_IMPLEMENTATION",`

You could also use RGFW.h instead of a .c file by changing it to

`"cflags": "-fPIE -x c -D RGFW_IMPLEMENTATION",`

I would also recommend against using c-types like `uint` and for you to use standard int types like `uint32_t` or `u32`
Although I've not checked if C3 has an alternative for this. 

Let me know if you have any questions about RGFW or if you need any help with the binding.

**Comment by tonis2** [comment]
Thanks for the suggestion @ColleagueRiley using -D flags, seems better way for sure.

I currently got stuck at creating Window struct for different OP systems,  surface / window pointers ..etc.
When creating window with void* the window is created fine, but I cant create surface based on void pointer.
Using my own Window struct causes crash :/
Maybe you have some insight how to solve this.

**Comment by ColleagueRiley** [comment]
It might be an issue with how the structure `RGFW_window_src` is arranged in memory. You can see [RGFW-Odin](https://github.com/ColleagueRiley/RGFW-Odin) as an example of how it should be organized. Although it might be a little out of date.

**Comment by tonis2** [comment]
I'm going to close this issue and we can perhaps continue here
https://github.com/tonis2/rgfw.c3
